### ISSUE TITLE
PyPi Source Distribution is Missing 'requirements.txt'

### ISSUE THREAD

**Issue by samuelchodur** [ISLA-UH/libwwz#1]
I was trying to install with pip directly from the file [libwwz-1.2.0.tar.gz](https://files.pythonhosted.org/packages/b5/d8/276f31bca275a07861ec5f57bc95c91d60ccd051dfd151f5e0a4b0f925d9/libwwz-1.2.0.tar.gz) which is hosted on PyPi. `requirements.txt` seems to be missing from the archive which leads to the following error:

```$ pip install libwwz-1.2.0.tar.gz
Processing ./libwwz-1.2.0.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-wmv5h48l/setup.py", line 3, in <module>
          with open("requirements.txt", "r") as requirements_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
The wheel file works as expected.

**Comment by NotKei** [comment]
Thank you for reporting this error!
We will be working on updating files on PyPi.

**Comment by NotKei** [comment]
A new release has been made that includes the requirement.txt!
https://pypi.org/project/libwwz/1.2.1/

Thank you again for making the issue!
